-- =====================================================
-- SECTION 1: Primary Key Assignment
-- =====================================================

-- Step 1: Create surrogate key for tables that don't have unique and not null keys in the original data tables

-- Table: Conditions
ALTER TABLE core.conditions
ADD COLUMN condition_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Table: Medications
ALTER TABLE core.medications 
ADD COLUMN medication_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Table: Observations
ALTER TABLE core.observations  
ADD COLUMN observation_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Table: Procedures
ALTER TABLE core.procedures   
ADD COLUMN procedure_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Table: Immunizations
ALTER TABLE core.immunizations    
ADD COLUMN immunization_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Table: Payer Transitions
ALTER TABLE core.payer_transitions   
ADD COLUMN payer_transition_sk BIGINT GENERATED BY DEFAULT AS IDENTITY;


--- Step 2: Assign Primary key to all the tables

ALTER TABLE core.patients 
ADD CONSTRAINT pk_patients
PRIMARY KEY (patient_id);

ALTER TABLE core.providers 
ADD CONSTRAINT pk_providers
PRIMARY KEY (provider_id);

ALTER TABLE core.organizations  
ADD CONSTRAINT pk_organizations
PRIMARY KEY (organization_id);

ALTER TABLE core.encounters 
ADD CONSTRAINT pk_encounters
PRIMARY KEY (encounter_id);

ALTER TABLE core.conditions 
ADD CONSTRAINT pk_conditions
PRIMARY KEY (condition_sk);

ALTER TABLE core.medications 
ADD CONSTRAINT pk_medications
PRIMARY KEY (medication_sk);

ALTER TABLE core.observations 
ADD CONSTRAINT pk_observations
PRIMARY KEY (observation_sk);

ALTER TABLE core.procedures 
ADD CONSTRAINT pk_procedures
PRIMARY KEY (procedure_sk);

ALTER TABLE core.immunizations 
ADD CONSTRAINT pk_immunizations
PRIMARY KEY (immunization_sk);

ALTER TABLE core.payers   
ADD CONSTRAINT pk_payers
PRIMARY KEY (payer_id);

ALTER TABLE core.payer_transitions   
ADD CONSTRAINT pk_payer_transitions
PRIMARY KEY (payer_transition_sk);

ALTER TABLE core.claims   
ADD CONSTRAINT pk_claims
PRIMARY KEY (claim_id);

ALTER TABLE core.claims_transactions   
ADD CONSTRAINT pk_claims_transactions
PRIMARY KEY (claim_transaction_id);


-- =====================================================
-- SECTION 2: Foreign Key Assignment
-- =====================================================


--- Table Conditions

ALTER TABLE core.conditions 
ADD CONSTRAINT fk_conditions_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core.conditions 
ADD CONSTRAINT fk_conditions_encounter
FOREIGN KEY (encounter_id)
REFERENCES core.encounters (encounter_id);


--- Table: Encounters

ALTER TABLE core.encounters 
ADD CONSTRAINT fk_encounters_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);


ALTER TABLE core.encounters 
ADD CONSTRAINT fk_encounters_organization
FOREIGN KEY (organization_id)
REFERENCES core.organizations (organization_id);


ALTER TABLE core.encounters 
ADD CONSTRAINT fk_encounters_provider
FOREIGN KEY (provider_id)
REFERENCES core.providers (provider_id);


ALTER TABLE core.encounters 
ADD CONSTRAINT fk_encounters_payer
FOREIGN KEY (payer_id)
REFERENCES core.payers (payer_id);


--- Table: Immunizations

ALTER TABLE core.immunizations  
ADD CONSTRAINT fk_immunizations_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core.immunizations 
ADD CONSTRAINT fk_immunizations_encounter
FOREIGN KEY (encounter_id)
REFERENCES core.encounters (encounter_id);


--- Table: Procedures

ALTER TABLE core."procedures"   
ADD CONSTRAINT fk_procedures_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core."procedures"  
ADD CONSTRAINT fk_procedures_encounter
FOREIGN KEY (encounter_id)
REFERENCES core.encounters (encounter_id);

--- Table: Medications

ALTER TABLE core.medications 
ADD CONSTRAINT fk_medications_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);


ALTER TABLE core.medications 
ADD CONSTRAINT fk_medications_encounter
FOREIGN KEY (encounter_id)
REFERENCES core.encounters (encounter_id);


ALTER TABLE core.medications 
ADD CONSTRAINT fk_medications_payer
FOREIGN KEY (payer_id)
REFERENCES core.payers (payer_id);


--- Table: Payer_Transition
ALTER TABLE core.payer_transitions 
ADD CONSTRAINT fk_payer_transitions_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);


--- Table: Provider
ALTER TABLE core.providers
ADD CONSTRAINT fk_providers_organization
FOREIGN KEY (organization_id)
REFERENCES core.organizations (organization_id);


--- Table: Claims
ALTER TABLE core.claims  
ADD CONSTRAINT fk_claims_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core.claims 
ADD CONSTRAINT fk_claims_provider
FOREIGN KEY (provider_id)
REFERENCES core.providers (provider_id);


--- Table: Claims_Transactions

ALTER TABLE core.claims_transactions 
ADD CONSTRAINT fk_claims_transactions_claim
FOREIGN KEY (claim_id)
REFERENCES core.claims (claim_id);

ALTER TABLE core.claims_transactions   
ADD CONSTRAINT fk_claims_transactions_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core.claims_transactions  
ADD CONSTRAINT fk_claims_transactions_provider
FOREIGN KEY (provider_id)
REFERENCES core.providers (provider_id);


--- Table: Observations

ALTER TABLE core.observations 
ADD CONSTRAINT fk_observations_patient
FOREIGN KEY (patient_id)
REFERENCES core.patients (patient_id);

ALTER TABLE core.observations 
ADD CONSTRAINT fk_observations_encounter
FOREIGN KEY (encounter_id)
REFERENCES core.encounters (encounter_id);


-- =====================================================
-- SECTION 3: Create Indexes
-- =====================================================

--- Table Encounters

CREATE INDEX idx_encounters_patient_id
ON core.encounters (patient_id);

CREATE INDEX idx_encounters_start
ON core.encounters (start_date);

CREATE INDEX idx_encounters_patient_start
ON core.encounters (patient_id, start_date);


---- Table Observations

CREATE INDEX idx_observations_patient_date
ON core.observations (patient_id, date_ts);

CREATE INDEX idx_observations_encounter_id
ON core.observations (encounter_id);

CREATE INDEX idx_observations_code
ON core.observations (observation_code);


---- Table Conditions

CREATE INDEX idx_conditions_code 
ON core.conditions (condition_code);

CREATE INDEX idx_conditions_patient_id 
ON core.conditions (patient_id);

CREATE INDEX idx_conditions_encounter_id 
ON core.conditions (encounter_id);

CREATE INDEX idx_conditions_patient_start
ON core.conditions (patient_id, start_date);


---- Table Medications

CREATE INDEX idx_medications_patient_id
ON core.medications (patient_id);

CREATE INDEX idx_medications_encounter_id
ON core.medications (encounter_id);

CREATE INDEX idx_medications_start
ON core.medications (start_ts);

CREATE INDEX idx_medications_code
ON core.medications (medication_code);

--- Claims ---
CREATE INDEX idx_claims_patient_id
ON core.claims (patient_id);


--- Claims_transaction ---

CREATE INDEX idx_claims_transactions_patient_id
ON core.claims_transactions (patient_id);

CREATE INDEX idx_claims_transactions_from_date
ON core.claims_transactions (from_date_ts);

CREATE INDEX idx_claims_transactions_claim_id
ON core.claims_transactions (claims_id);

